services:
  - type: web
    name: gold-price-checker-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir api server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: COOKIE_SECURE
        value: "true"
      - key: APP_ENV
        value: production
